/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.priyakdey;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class ConfigurationServerTest {

    @Test
    void contextLoads(){
        // Empty Test. If passes, means the AppContext config is correct.
    }
}
