# This workflow will build the Java project with Gradle
# For workflow basics: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# For Java: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: Java CI with Gradle

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 16
          uses: actions/setup-java@v2
          with:
              java-version: '16'
              distribution: 'zulu'
        - name: Grant Execute permission for wrapper
          run: chmod +x gradlew
        - name: Build application
          run: ./gradlew build
        - name: Run test cases
          run: ./gradlew test

